DROP TABLE s_hajo CASCADE CONSTRAINTS;

DROP TABLE s_hajo_tipus CASCADE CONSTRAINTS;

DROP TABLE s_helyseg CASCADE CONSTRAINTS;

DROP TABLE s_hozzarendel CASCADE CONSTRAINTS;

DROP TABLE s_kikoto CASCADE CONSTRAINTS;

DROP TABLE s_kikoto_telefon CASCADE CONSTRAINTS;

DROP TABLE s_megrendeles CASCADE CONSTRAINTS;

DROP TABLE s_orszag CASCADE CONSTRAINTS;

DROP TABLE s_szallit CASCADE CONSTRAINTS;

DROP TABLE s_ugyfel CASCADE CONSTRAINTS;

DROP TABLE s_ut CASCADE CONSTRAINTS;